Oprydning/Buffet_GUI/Models/ErrorViewModel.cs
using System;

namespace Buffet_GUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Oprydning/Buffet_GUI/Models/KitchenViewModel.cs
using Buffet_GUI.Data.DBModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Buffet_GUI.Models
{
    public class KitchenViewModel
    {
        public KitchenViewModel(List<BuffetReservation> expectedGuestsInfo, List<CheckedInGuest> checkedInEntries)
        {
            var TotalChildren = 0;
            var TotalAdults = 0;
            var TotalCheckedIn = 0;

            var TotalChildrenExpected = 0;
            var TotalAdultsExpected = 0;
            var TotalCheckedInExpected = 0;

            checkedInEntries.ForEach(g =>
            {
                TotalChildren += g.NumberOfChildrenCheckedIn;
                TotalAdults += g.NumberOfAdultsCheckedIn;
            });

            TotalCheckedIn = TotalAdults + TotalChildren;

            expectedGuestsInfo.ForEach(g =>
            {
                TotalChildrenExpected += g.NumberOfChildren;
                TotalAdultsExpected += g.NumberOfAdults;
                TotalCheckedInExpected += g.AllExpectedGuests;
            });
            
            TotalChildrenNotCheckedIn = TotalChildrenExpected - TotalChildren;
            TotalAdultsNotCheckedIn = TotalAdultsExpected - TotalAdults;
            TotalNotCheckedIn = TotalCheckedInExpected - TotalCheckedIn;
        }
        public int TotalChildrenNotCheckedIn { get; set; }
        public int TotalAdultsNotCheckedIn { get; set; }
        public int TotalNotCheckedIn { get; set; }

    }
}

Oprydning/Buffet_GUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Buffet_GUI.Models;

namespace Buffet_GUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Oprydning/Buffet_GUI/Controllers/KitchenController.cs
using Buffet_GUI.Data;
using Buffet_GUI.Data.DBModels;
using Buffet_GUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Buffet_GUI.Controllers
{
    public class KitchenController : Controller
    {
        private readonly ApplicationDbContext _context;

        
        public KitchenController(ApplicationDbContext context)
        {
            _context = context;
        }
        [Authorize("CanEnterKitchen")]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize("CanEnterKitchen")]
        public IActionResult ShowBuffetReservationsExpected(DateTime dateTime)
        {
            DateTime date = dateTime.Date;

            var restaurantCheckIns = _context.Set<BuffetReservation>().Where(c => (c.Date.Day == date.Day) && (c.Date.Month == date.Month) && (c.Date.Year == date.Year)).ToList();

            return View(restaurantCheckIns);
        }

        [Authorize("CanEnterKitchen")]
        /* Given date, show guest-information (expected amount, checked-in amount, etc.) */
        public IActionResult ShowNotCheckInGuests(DateTime dateTime)
        {
            DateTime date = dateTime.Date;

            var expectedGuestsInfo = _context.Set<BuffetReservation>().Where(c => (c.Date.Day == date.Day) && (c.Date.Month == date.Month) && (c.Date.Year == date.Year)).ToList();
            var checkedInEntries = _context.Set<CheckedInGuest>().Where(c => c.Date == date).ToList();

            var vm = new KitchenViewModel(expectedGuestsInfo, checkedInEntries);

            return View(vm);

        }
    }
}

Oprydning/Buffet_GUI/Controllers/ReceptionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using Buffet_GUI.Data;
using Buffet_GUI.Data.DBModels;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Buffet_GUI.Controllers
{
    public class ReceptionController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReceptionController(ApplicationDbContext context)
        {
            _context = context;
        }


        [Authorize("CanEnterReception")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.BuffetReservations.ToListAsync());
        }

        [Authorize("CanEnterReception")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize("CanEnterReception")]
        public IActionResult Reception()
        {
            return View();
        }
        
        public IActionResult ShowCheckedInBuffetList(DateTime dateTime)
        {
            DateTime date = dateTime.Date;     
            
            var restaurantCheckIns = _context.Set<CheckedInGuest>().Where(c => c.Date == date).ToList();

            return View(restaurantCheckIns);
        }

        [Authorize("CanEnterReception")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AllExpectedGuests,NumberOfAdults,NumberOfChildren,Date")] BuffetReservation buffetReservation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(buffetReservation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(buffetReservation);
        }
    }
}

Oprydning/Buffet_GUI/Controllers/RestaurantController.cs
using Buffet_GUI.Data;
using Buffet_GUI.Data.DBModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Buffet_GUI.Controllers
{
    public class RestaurantController : Controller
    {
        [Authorize("CanEnterRestaurant")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.CheckedInGuests.ToListAsync());
        }

        private readonly ApplicationDbContext _context;

        public RestaurantController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize("CanEnterRestaurant")]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize("CanEnterRestaurant")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoomNumber,NumberOfAdultsCheckedIn,NumberOfChildrenCheckedIn,Date")] CheckedInGuest checkedInGuest)
        {
            if (ModelState.IsValid)
            {
                _context.Add(checkedInGuest);
                await _context.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }
            
            return View(checkedInGuest);
        }     

    }
}

Oprydning/Buffet_GUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>
    <link rel="stylesheet" href="css/StyleSheet.css" />
</head>

<div class="text-center">
    <h2 class="display-4">Welcome to the morningbuffet system:</h2>
    <p>If there are no buttons beyond register and login in the Navbar, you aren't logged in, or your user does not have access to the system. If you mean you should have access, contact the systemadmin for a solution</p>
    <b>Alloted staff for the system at the moment are Kitchen, Reception and Restaurant staff!</b>
</div>

Oprydning/Buffet_GUI/Views/Kitchen/Index.cshtml
@model IEnumerable<Buffet_GUI.Data.DBModels.BuffetReservation>
@{
    ViewData["Title"] = "Index";
}

<head>
    <link rel="stylesheet" href="css/StyleSheet.css"/>
</head>

<h2>Welcome Kitchen staff to the Kitchen main page:</h2>

<form asp-action="ShowBuffetReservationsExpected" method="get">
    <div class="form-group">
        <label class="control-label">Search for expected guests on a specific day: </label>

        <input type="date" name="datetime" class="form-control col-md-6" />
    </div>

    <div class="form-group">
        <input type="submit" class="button" value="Search" />
    </div>
</form>

<form asp-controller="Reception" asp-action="ShowCheckedInBuffetList" method="get">
    <div class="form-group">
        <label class="control-label">Search for checked in guests on a specific day:</label>

        <input type="date" name="datetime" class="form-control col-md-6" />
    </div>
    <div class="form-group">
        <input type="submit" class="button" value="Search" />
    </div>
</form>

<form asp-controller="Kitchen" asp-action="ShowNotCheckInGuests" method="get">
    <div class="form-group">
        <label class="control-label">Search for non-checked in guests on a specific day:</label>

        <input type="date" name="datetime" class="form-control col-md-6" />
    </div>
    <div class="form-group">
        <input type="submit" class="button" value="Search" />
    </div>
</form>

Oprydning/Buffet_GUI/Views/Kitchen/ShowBuffetReservationsExpected.cshtml
@model IEnumerable<Buffet_GUI.Data.DBModels.BuffetReservation>
@{
    ViewData["Title"] = "ShowBuffetReservationsExpected";
}
<head>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
</head>

<h2>Exptected guests on the given day:</h2>

<table class="table">
    <thead>
        <tr>
            <link rel="stylesheet" href="css/StyleSheet.css" />
            <th>
                @Html.DisplayNameFor(model => model.AllExpectedGuests)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfAdults)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfChildren)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AllExpectedGuests)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfAdults)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfChildren)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date.Date)
                </td>
            </tr>
        }
    </tbody>
</table>

<button class="button" onClick="window.location.reload();">Refresh Page</button>

Oprydning/Buffet_GUI/Views/Kitchen/ShowNotCheckInGuests.cshtml
@model Buffet_GUI.Models.KitchenViewModel

@{
    ViewData["Title"] = "ShowNotCheckInGuests";
}
<head>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
</head>

<h2>Guests not checked in yet on the given date: </h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TotalChildrenNotCheckedIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalAdultsNotCheckedIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalNotCheckedIn)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.TotalChildrenNotCheckedIn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.TotalAdultsNotCheckedIn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.TotalNotCheckedIn)
                </td>

            </tr>
        
    </tbody>
</table>

<button class="button" onClick="window.location.reload();">Refresh Page</button>

Oprydning/Buffet_GUI/Views/Reception/Create.cshtml
@model Buffet_GUI.Data.DBModels.BuffetReservation

@{
    ViewData["Title"] = "Create";
}
<head>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
</head>

<b>Create exptected guest entry</b>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AllExpectedGuests" class="control-label"></label>
                <input asp-for="AllExpectedGuests" class="form-control" />
                <span asp-validation-for="AllExpectedGuests" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfAdults" class="control-label"></label>
                <input asp-for="NumberOfAdults" class="form-control" />
                <span asp-validation-for="NumberOfAdults" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfChildren" class="control-label"></label>
                <input asp-for="NumberOfChildren" class="form-control" />
                <span asp-validation-for="NumberOfChildren" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="button" />
            </div>
        </form>
    </div>
</div>

<form asp-action="Index" method="get">
    <div>
        <button class="button"> Back to List </button>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Oprydning/Buffet_GUI/Views/Reception/Index.cshtml
@model IEnumerable<Buffet_GUI.Data.DBModels.BuffetReservation>

@{
    ViewData["Title"] = "Index";
}
<head>
    <link rel="stylesheet" href="css/StyleSheet.css" />
</head>

<b>Below it is possible to add expected guests for a given day, and inspect expected guests for all entrys per day</b>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AllExpectedGuests)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfAdults)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfChildren)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AllExpectedGuests)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfAdults)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfChildren)
                </td>
            </tr>
        }
    </tbody>
</table>


<form asp-controller="Reception" asp-action="Create" method="get">
    <div>
        <button class="button"> Add expected guests for a given day </button>
    </div>
</form>

Oprydning/Buffet_GUI/Views/Reception/Reception.cshtml
@model IEnumerable<Buffet_GUI.Data.DBModels.CheckedInGuest>
@{
    ViewData["Title"] = "Reception";
}
<head>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
</head>


<h2>Welcome Restarant staff to the Restarant main page!</h2>

<form asp-action="ShowCheckedInBuffetList" method="get">
    <div class="form-group">
        <label class="control-label">Search for allready checked in guests:</label>
        <input type="date" name="dateTime" class="form-control col-md-6" />
    </div>

    <div class="form-group">
        <input type="submit" class="button" value="Search" />
    </div>
</form>

<form asp-controller="Reception" asp-action="Create" method="get">
    <div>
        <button class="button" > Add Expected Guests </button>
    </div>
</form>

Oprydning/Buffet_GUI/Views/Reception/ShowCheckedInBuffetList.cshtml
@model IEnumerable<Buffet_GUI.Data.DBModels.CheckedInGuest>
@{
    ViewData["Title"] = "ShowCheckedInBuffetList";
}
<head>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
</head>

<h2>Checked in guests: </h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RoomNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfAdultsCheckedIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfChildrenCheckedIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RoomNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfAdultsCheckedIn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfChildrenCheckedIn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
            </tr>
        }
    </tbody>
</table>

<button class="button" onClick="window.location.reload();">Refresh Page</button>

Oprydning/Buffet_GUI/Views/Restaurant/Create.cshtml
@model Buffet_GUI.Data.DBModels.CheckedInGuest

@{
    ViewData["Title"] = "Create";
}
<head>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
</head>

<h2>Welcome Restarant staff to the Restarant main page!</h2>
<b>Below you can check in guests for the kitchen, with the expected guests for a given day:</b>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoomNumber" class="control-label"></label>
                <input asp-for="RoomNumber" class="form-control" />
                <span asp-validation-for="RoomNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfAdultsCheckedIn" class="control-label"></label>
                <input asp-for="NumberOfAdultsCheckedIn" class="form-control" />
                <span asp-validation-for="NumberOfAdultsCheckedIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfChildrenCheckedIn" class="control-label"></label>
                <input asp-for="NumberOfChildrenCheckedIn" class="form-control" />
                <span asp-validation-for="NumberOfChildrenCheckedIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="button" />
            </div>
        </form>
    </div>
</div>


<form asp-action="Index" method="get">
    <div>
        <button class="button"> Back to List </button>
    </div>
</form>

Oprydning/Buffet_GUI/Views/Restaurant/Index.cshtml
@model IEnumerable<Buffet_GUI.Data.DBModels.CheckedInGuest>

@{
    ViewData["Title"] = "Index";
}

<head>
    <link rel="stylesheet" href="css/StyleSheet.css" />
</head>


<h1>Welcome Restarant staff to the Restarant main page!</h1>
    <b>Below you can check in guests for the kitchen, and inspect the expected guests:</b>

<form asp-action="Create" method="get">
    <div>
        <button class="button"> Check in guests </button>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfAdultsCheckedIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfChildrenCheckedIn)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfAdultsCheckedIn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfChildrenCheckedIn)
                </td>
            </tr>
        }
    </tbody>
</table>

Oprydning/Buffet_GUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Buffet_GUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="lib/bootstrap-datepicker/css/bootstrap-datepicker.min.css"/>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
<header>
    <link rel="stylesheet" href="css/StyleSheet.css"/>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Buffet_GUI</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    @if ((await AuthorizationService.AuthorizeAsync(User, "CanEnterReception")).Succeeded)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reception" asp-action="Reception">Reception</a>
                        </li>
                    }
                    @if ((await AuthorizationService.AuthorizeAsync(User, "CanEnterKitchen")).Succeeded)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kitchen" asp-action="Index">Kitchen</a>
                        </li>
                    }
                    @if ((await AuthorizationService.AuthorizeAsync(User, "CanEnterRestaurant")).Succeeded)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="Create">Restaurant</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Buffet_GUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
@RenderSection("Scripts", required: false)
</body>
</html>